usethis::use_package( "ggplot2" )
usethis::use_package( "dplyr" )
usethis::use_package( "stringr" )
usethis::use_package( "DT" )
usethis::use_package( "shinydashboard" )
usethis::use_package( "shinyWidgets" )
usethis::use_package( "shinycustomloader" )
usethis::use_package( "RColorBrewer" )
usethis::use_package( "logging" )
golem::add_module( name = "data_import" )
golem::add_module( name = "backtracking" )
golem::add_module( name = "plate_specifications")
golem::add_fct( "constraints" )
golem::add_fct( "generate_map" )
golem::add_fct( "draw_map" )
golem::add_fct( "conversion" )
golem::add_fct( "blank_coordinates" )
golem::add_fct( "solve_cell" )
golem::add_fct( "random_walk" )
golem::add_fct( "balanced_distribution" )
golem::add_fct( "resample" )


# golem::add_utils( "helpers" )
# golem::add_js_file( "script" )
# golem::add_js_handler( "handlers" )
golem::add_css_file( "custom" )
# usethis::use_data_raw( name = "my_dataset", open = FALSE ) 
usethis::use_test( "app" )
usethis::use_vignette("wpm3")
devtools::build_vignettes()
usethis::use_github()
usethis::use_travis()
usethis::use_appveyor()
rstudioapi::navigateToFile("dev/03_deploy.R")
