devtools::check()
rhub::check_for_cran()
golem::add_rstudioconnect_file()
golem::add_shinyappsio_file()
golem::add_shinyserver_file()
golem::add_dockerfile()
golem::add_dockerfile_shinyproxy()
golem::add_dockerfile_heroku()
